"""Pydantic 数据模型。三份 JSON Schema 的运行时对应物。"""

from .job import Job, JobEvent, JobKind, JobStatus, JobTable
from .manifest import (
    AnimationEntry,
    AssetManifest,
    BackgroundInfo,
    DerivedAnimation,
    GeneratedAnimation,
    GridInfo,
    PaletteInfo,
    StaticImageInfo,
)
from .pack import (
    PACK_ASSET_TYPES,
    PackAsset,
    PackPalette,
    PackShared,
    StaticAssetPack,
    expand_pack,
    input_fingerprint,
    load_pack,
    parse_pack,
)
from .request import (
    STATIC_ASSET_TYPES,
    AnimationSpec,
    AssetRequest,
    BackgroundSpec,
    ExportSpec,
    MirroringSpec,
    StyleSpec,
    load_request,
    parse_request,
)
from .validation import Check, CheckId, CheckResult, Severity, ValidationReport

__all__ = [
    "PACK_ASSET_TYPES",
    "STATIC_ASSET_TYPES",
    "AnimationEntry",
    "AnimationSpec",
    "AssetManifest",
    "AssetRequest",
    "BackgroundInfo",
    "BackgroundSpec",
    "Check",
    "CheckId",
    "CheckResult",
    "DerivedAnimation",
    "ExportSpec",
    "GeneratedAnimation",
    "GridInfo",
    "Job",
    "JobEvent",
    "JobKind",
    "JobStatus",
    "JobTable",
    "MirroringSpec",
    "PackAsset",
    "PackPalette",
    "PackShared",
    "PaletteInfo",
    "Severity",
    "StaticAssetPack",
    "StaticImageInfo",
    "StyleSpec",
    "ValidationReport",
    "expand_pack",
    "input_fingerprint",
    "load_pack",
    "load_request",
    "parse_pack",
    "parse_request",
]
